version: "3.9"
services:
  nginx:
    extends:
      file: docker-compose.base.yml
      service: nginx
    volumes:
      - ./docker/nginx/conf.d/modx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  php-fpm:
    extends:
      file: docker-compose.base.yml
      service: php-fpm

  mysql:
    extends:
      file: docker-compose.base.yml
      service: mysql
    ports:
      - "3306:3306"
